
import './globals.css'
import ThemeProvider from "./components/ui/ThemeProvider/ThemeProvider";

import {ClientProvider} from "~/client/trpcClient";


function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <ClientProvider>
            <html lang="en">
            <head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </head>

            <body>

            <ThemeProvider>
                {children}
            </ThemeProvider>
            </body>

            </html>
        </ClientProvider>

    )
}

export default RootLayout;